---
# A default configuration file

# Configuration for manifest check
manifest_sec:
  # Manifest max size to check
  CFG_MANIFEST_MAX_SIZE: 40000
  # Manifest extensions to check
  CFG_FILE_NAME_EXTS: .html, .txt
  # threshold for the notifications
  CFG_TERM_PERC_TH: 100

# Configuration for random check
random_sec:
  # compression percentage threshold
  CFG_COMPR_RAND_TH: 0.70
  # binary entropy threshold [0,8]
  CFG_ENTR_RAND_TH: 7.80
  # bytes content limit to check (None is for no limit)
  CFG_N_BYTES_2_RAND_CHECK: -1
  # minimum bytes to check a compressed content
  CFG_COMPRESSED_CONTENT_MIN_LEN: 100

  # configuration for magic number exclusion euristic
  magic_n_sec:
    # file path for the stored signatures and magic numbers
    CFG_PATH_FOR_SIGNATURES: ./file_sigs.pickle
    # the maximum length to check for the magic number
    CFG_MAX_FILE_SIGNATURE_LENGTH: 60

# configuration for mail notifications
mail_sec:
  CFG_SMTP_SSL: false
  CFG_SMTP_HOST: smtp.gmail.com
  CFG_SMTP_PORT: 465
  CFG_SMTP_USER: an.email@something.com
  CFG_SMTP_PWD: an.email.password